language: java
sudo: false
install: true

jdk:
  - oraclejdk7

script: mvn verify -Dmaven.test.redirectTestOutputToFile=false -B -e -V

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
